obj-$(CONFIG_NATIONALCHIP_COUNTER) += nc_counter.o

ifeq ($(CONFIG_NATIONALCHIP_NPU), y)
	obj-$(CONFIG_NATIONALCHIP_NPU) += npu.o
endif

ifeq ($(CONFIG_NATIONALCHIP_GXAVDEV), y)
	obj-$(CONFIG_NATIONALCHIP_GXAVDEV) += gxavdev.o
endif

