ifeq ($(CONFIG_NATIONALCHIP_GXASOC), y)
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_platform.o
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_platform_dai.o
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_codec.o
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_machine.o
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_npcp215x.o
	obj-$(CONFIG_NATIONALCHIP_GXASOC) += gx_asoc_nau8822.o
endif
