snd-soc-gx-platform-objs := pcm.o core.o stream.o control.o
snd-soc-gx-platform-dai-objs := dai.o
snd-soc-gx-machine-objs := machine.o

obj-$(CONFIG_SND_SOC_NATIONALCHIP) += snd-soc-gx-platform.o
obj-$(CONFIG_SND_SOC_NATIONALCHIP) += snd-soc-gx-platform-dai.o
obj-$(CONFIG_SND_SOC_NATIONALCHIP) += snd-soc-gx-machine.o
